app/models.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/30 15:34
# @Author  : WANGXIAO

# 会员模型

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import mysql.connector

app = Flask(__name__)

app.config["SQLALCHEMY_DATABASE_URI"] = "mysql+mysqlconnector://root:123456@localhost:3306/d_movie"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = True

db = SQLAlchemy(app)


# 会员
class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)  # 会员id  主键
    name = db.Column(db.String(100), unique=True)  # 会员名 唯一值
    pwd = db.Column(db.String(100))  # 密码
    email = db.Column(db.String(100), unique=True)  # 邮箱
    phone = db.Column(db.String(100), unique=True)  # 手机号码
    info = db.Column(db.Text)  # 个性简介
    face = db.Column(db.String(255))  # 头像
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 日期
    uuid = db.Column(db.String(255), unique=True)  # 唯一标识

    # 增加外键,会员与会员日志建立关系
    userlogs = db.relationship('UserLog', backref='user')
    comments = db.relationship('Comment', backref='user')
    moviecols = db.relationship('MovieCol', backref='user')

    def __repr__(self):
        return "<User %r>" % self.name


# 会晕登录日志
class UserLog(db.Model):
    __tablename__ = 'userlog'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))  # 所属会员
    ip = db.Column(db.String(100))  # 登录ip
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 登录日期

    def __repr__(self):
        return "<UserLog %r>" % self.user_id


# 标签
class Tag(db.Model):
    __tablename__ = 'tag'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    name = db.Column(db.String(100), unique=True)  # 标签名 唯一值
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 登录日期
    # 增加movie外键
    movies = db.relationship('Movie', backref='movie')

    def __repr__(self):
        return "<Tag %r>" % self.name


# 电影
class Movie(db.Model):
    __tablename__ = 'movie'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    title = db.Column(db.String(255), unique=True)  # 电影标题
    url = db.Column(db.String(255), unique=True)  # 电影地址
    info = db.Column(db.Text)  # 电影简介
    logo = db.Column(db.String(255), unique=True)  # 电影标题
    star = db.Column(db.SmallInteger)  # 星级
    playnum = db.Column(db.BigInteger)  # 播放量
    commentnum = db.Column(db.BigInteger)  # 评论数
    tag_id = db.Column(db.Integer, db.ForeignKey('tag.id'))  # 所属tagid
    area = db.Column(db.String(255))  # 上映地区
    release_time = db.Column(db.DateTime)  # 上映时间
    length = db.Column(db.String(255))  # 播放时间
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 添加日期

    # 添加外键
    comments = db.relationship('Comment', backref='movie')
    moviecol = db.relationship('MovieCol', backref='movie')

    def __repr__(self):
        return "<Movie %r>" % self.title


# 上映预告
class Preview(db.Model):
    __tablename__ = 'preview'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    title = db.Column(db.String(255), unique=True)  # 电影标题
    logo = db.Column(db.String(255), unique=True)  # 电影标题
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 添加日期

    def __repr__(self):
        return "<Preview %r>" % self.title


# 评论
class Comment(db.Model):
    __tablename__ = 'comment'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    content = db.Column(db.Text)  # 评论内容
    movie_id = db.Column(db.Integer, db.ForeignKey('movie.id'))  # 外键链接movie.id
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))  # 外键user.id
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 添加日期

    def __repr__(self):
        return "<Comment %r>" % self.id


# 电影收藏
class MovieCol(db.Model):
    __tablename__ = 'moviecol'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    movie_id = db.Column(db.Integer, db.ForeignKey('movie.id'))  # 外键链接movie.id
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))  # 外键user.id
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 添加日期

    def __repr__(self):
        return "<MovieCol %r>" % self.id


# 权限
class Auth(db.Model):
    __tablename__ = 'auth'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    name = db.Column(db.String(255), unique=True)  # 用户
    url = db.Column(db.String(255), unique=True)  # url
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 添加日期

    def __repr__(self):
        return "<Auth %r>" % self.id


# 角色
class Role(db.Model):
    __tablename__ = 'role'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    name = db.Column(db.String(255), unique=True)  # 角色名
    auths = db.Column(db.String(255))  # 权限列表
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 添加日期

    # 添加外键
    admins = db.relationship('Admin', backref='role')

    def __repr__(self):
        return "<Role %r>" % self.name


# 管理员
class Admin(db.Model):
    __tablename__ = 'admin'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    name = db.Column(db.String(255), unique=True)  # 管理员
    pwd = db.Column(db.String(255))
    is_super = db.Column(db.SmallInteger)  # 是否继承
    role_id = db.Column(db.Integer, db.ForeignKey('role.id'))  # 外键role.id
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 添加日期

    # 添加外键
    adminlogs = db.relationship('AdminLog', backref='admin')
    operatelogs = db.relationship('OperateLog', backref='admin')

    def __repr__(self):
        return "<Admin %r>" % self.name


# 管理员日志
class AdminLog(db.Model):
    __tablename__ = 'adminlog'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    admin_id = db.Column(db.Integer, db.ForeignKey('admin.id'))  # 所属管理员
    ip = db.Column(db.String(100))  # 登录ip
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 登录日期

    def __repr__(self):
        return "<AdminLog %r>" % self.admin_id


# 操作日志
class OperateLog(db.Model):
    __tablename__ = 'operatelog'
    id = db.Column(db.Integer, primary_key=True)  # 编号
    admin_id = db.Column(db.Integer, db.ForeignKey('admin.id'))  # 所属管理员
    ip = db.Column(db.String(100))  # 登录ip
    reason = db.Column(db.String(600))
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)  # 登录日期

    def __repr__(self):
        return "<OperateLog %r>" % self.id


if __name__ == '__main__':
    # db.create_all()
    role = Role(
        name="超级管理员",
        auths=""
    )
    db.session.add(role)
    db.session.commit()

    from werkzeug.security import generate_password_hash

    admin = Admin(
        name="wangxiao",
        pwd=generate_password_hash('wangxiao'),
        is_super=0,
        role_id=1
    )
    db.session.add(admin)
    db.session.commit()

app/admin/forms.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/30 15:35
# @Author  : WANGXIAO

app/home/forms.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/30 15:35
# @Author  : WANGXIAO

app/__init__.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/30 15:33
# @Author  : WANGXIAO
# 注册蓝图
from flask import Flask

app = Flask(__name__)

app.debug = True

from app.home import home as home_blueprint
from app.admin import admin as admin_blueprint

app.register_blueprint(home_blueprint)
app.register_blueprint(admin_blueprint, url_prefix='/admin')

app/admin/__init__.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/30 15:33
# @Author  : WANGXIAO
from flask import Blueprint

admin = Blueprint('admin', __name__)

import app.admin.views

app/admin/views.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/30 15:35
# @Author  : WANGXIAO

from . import admin


@admin.route('/')
def index():
    return "<h1 style='color:green'>this is flask admin</h1>"

app/home/__init__.py
# -*- coding: utf-8 -*-
# @Time    : 2019/1/30 15:33
# @Author  : WANGXIAO

from flask import Blueprint

home = Blueprint('home', __name__)

import app.home.view

app/templates/home/comments.html
{% extends "home/home.html" %}


{% block content %}
{% include "home/menu.html" %}
<div class="col-md-9">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;评论记录</h3>
        </div>
        <div class="panel-body">
            <ul class="commentList">
                <li class="item cl">
                    <a href="user.html">
                        <i class="avatar size-L radius">
                            <img alt="50x50" src="holder.js/50x50" class="img-circle" style="border:1px solid #abcdef;">
                        </i>
                    </a>
                    <div class="comment-main">
                        <header class="comment-header">
                            <div class="comment-meta">
                                <a class="comment-author" href="user.html">xiaoli</a>
                                评论于
                                <time title="2016-12-07 09:12:51" datetime="2016-12-07 09:12:51">2017-03-01 09:12:51
                                </time>
                            </div>
                        </header>
                        <div class="comment-body">
                            <p>这电影真好看！</p>
                        </div>
                    </div>
                </li>
                <li class="item cl">
                    <a href="user.html">
                        <i class="avatar size-L radius">
                            <img alt="50x50" src="holder.js/50x50" class="img-circle" style="border:1px solid #abcdef;">
                        </i>
                    </a>
                    <div class="comment-main">
                        <header class="comment-header">
                            <div class="comment-meta">
                                <a class="comment-author" href="user.html">xiaoli</a>
                                评论于
                                <time title="2016-12-07 09:12:51" datetime="2016-12-07 09:12:51">2017-03-01 09:12:51
                                </time>
                            </div>
                        </header>
                        <div class="comment-body">
                            <p>这电影真好看！</p>
                        </div>
                    </div>
                </li>
                <li class="item cl">
                    <a href="user.html">
                        <i class="avatar size-L radius">
                            <img alt="50x50" src="holder.js/50x50" class="img-circle" style="border:1px solid #abcdef;">
                        </i>
                    </a>
                    <div class="comment-main">
                        <header class="comment-header">
                            <div class="comment-meta">
                                <a class="comment-author" href="user.html">xiaoli</a>
                                评论于
                                <time title="2016-12-07 09:12:51" datetime="2016-12-07 09:12:51">2017-03-01 09:12:51
                                </time>
                            </div>
                        </header>
                        <div class="comment-body">
                            <p>这电影真好看！</p>
                        </div>
                    </div>
                </li>
                <li class="item cl">
                    <a href="user.html">
                        <i class="avatar size-L radius">
                            <img alt="50x50" src="holder.js/50x50" class="img-circle" style="border:1px solid #abcdef;">
                        </i>
                    </a>
                    <div class="comment-main">
                        <header class="comment-header">
                            <div class="comment-meta">
                                <a class="comment-author" href="user.html">xiaoli</a>
                                评论于
                                <time title="2016-12-07 09:12:51" datetime="2016-12-07 09:12:51">2017-03-01 09:12:51
                                </time>
                            </div>
                        </header>
                        <div class="comment-body">
                            <p>这电影真好看！</p>
                        </div>
                    </div>
                </li>
                <li class="item cl">
                    <a href="user.html">
                        <i class="avatar size-L radius">
                            <img alt="50x50" src="holder.js/50x50" class="img-circle" style="border:1px solid #abcdef;">
                        </i>
                    </a>
                    <div class="comment-main">
                        <header class="comment-header">
                            <div class="comment-meta">
                                <a class="comment-author" href="user.html">xiaoli</a>
                                评论于
                                <time title="2016-12-07 09:12:51" datetime="2016-12-07 09:12:51">2017-03-01 09:12:51
                                </time>
                            </div>
                        </header>
                        <div class="comment-body">
                            <p>这电影真好看！</p>
                        </div>
                    </div>
                </li>
            </ul>
            <div class="col-md-12 text-center">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="First">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                        </li>
                        <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Last">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }

    </style>
    <style>
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="index.html" class="navbar-brand" style="width:250px;">
                <img src="../static/base/images/logo.png" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="search.html"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
{% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2019&nbsp;
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>
{% block js %}{% endblock %}
</body>
</html>


app/templates/home/index.html
{% extends "home/home.html" %}

{% block content %}
<h1>hello world</h1>
{% endblock %}

app/templates/home/login.html
{% extends "home/home.html" %}
{% block content %}
<div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-log-in"></span>&nbsp;会员登录</h3>
                </div>
                <div class="panel-body">
                    <form role="form">
                        <fieldset>
                            <div class="form-group">
                                <label for="input_contact"><span class="glyphicon glyphicon-user"></span>&nbsp;账号</label>
                                <input id="input_contact" class="form-control input-lg" placeholder="用户名/邮箱/手机号码" name="contact" type="text" autofocus>
                            </div>
                            <div class="col-md-12" id="error_contact"></div>
                            <div class="form-group">
                                <label for="input_password"><span class="glyphicon glyphicon-lock"></span>&nbsp;密码</label>
                                <input id="input_password" class="form-control input-lg" placeholder="密码" name="password" type="password" value="">
                            </div>
                            <div class="col-md-12" id="error_password"></div>
                            <a href="user.html" class="btn btn-lg btn-success btn-block">登录</a>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/home/loginlog.html
{% extends "home/home.html" %}


{% block content %}
{% include "home/menu.html" %}
<div class="col-md-9">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;登录日志</h3>
        </div>
        <div class="panel-body">
            <table class="table table-bordered">
                <tr>
                    <td style="width:10%">编号</td>
                    <td style="width:30%">登录时间</td>
                    <td style="width:30%">登录IP</td>
                    <td style="width:30%">登录地址</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2017-01-01 12:00:00</td>
                    <td>192.168.4.1</td>
                    <td>云南昆明</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2017-01-01 12:00:00</td>
                    <td>192.168.4.1</td>
                    <td>云南昆明</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2017-01-01 12:00:00</td>
                    <td>192.168.4.1</td>
                    <td>云南昆明</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2017-01-01 12:00:00</td>
                    <td>192.168.4.1</td>
                    <td>云南昆明</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2017-01-01 12:00:00</td>
                    <td>192.168.4.1</td>
                    <td>云南昆明</td>
                </tr>

            </table>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{url_for('home.user')}}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="m-2" href="{{url_for('home.pwd')}}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{url_for('home.comments')}}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{url_for('home.loginlog')}}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{url_for('home.moviecol')}}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>

app/templates/home/moviecol.html
{% extends "home/home.html" %}


{% block content %}
{% include "home/menu.html" %}
<div class="col-md-9">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;收藏电影</h3>
        </div>
        <div class="panel-body">
            <div class="col-md-12">
                <div class="media">
                    <div class="media-left">
                        <a href="play.html">
                            <img class="media-object" src="holder.js/131x83" alt="环太平洋">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">环太平洋<a href="play.html" class="label label-primary pull-right"><span
                                class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                        该片主要讲述了人类为了抵抗怪兽的进攻，研制出了高大的机器战士与来犯怪兽进行对抗的故事。
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <a href="play.html">
                            <img class="media-object" src="holder.js/131x83" alt="环太平洋">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">环太平洋<a href="play.html" class="label label-primary pull-right"><span
                                class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                        该片主要讲述了人类为了抵抗怪兽的进攻，研制出了高大的机器战士与来犯怪兽进行对抗的故事。
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <a href="play.html">
                            <img class="media-object" src="holder.js/131x83" alt="环太平洋">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">环太平洋<a href="play.html" class="label label-primary pull-right"><span
                                class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                        该片主要讲述了人类为了抵抗怪兽的进攻，研制出了高大的机器战士与来犯怪兽进行对抗的故事。
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <a href="play.html">
                            <img class="media-object" src="holder.js/131x83" alt="环太平洋">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">环太平洋<a href="play.html" class="label label-primary pull-right"><span
                                class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                        该片主要讲述了人类为了抵抗怪兽的进攻，研制出了高大的机器战士与来犯怪兽进行对抗的故事。
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <a href="play.html">
                            <img class="media-object" src="holder.js/131x83" alt="环太平洋">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">环太平洋<a href="play.html" class="label label-primary pull-right"><span
                                class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                        该片主要讲述了人类为了抵抗怪兽的进攻，研制出了高大的机器战士与来犯怪兽进行对抗的故事。
                    </div>
                </div>
            </div>
            <div class="col-md-12 text-center" style="margin-top:6px;">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="First">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                        </li>
                        <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Last">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/pwd.html
{% extends "home/home.html" %}


{% block content %}
{% include "home/menu.html" %}
<div class="col-md-9">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;会员中心</h3>
        </div>
        <div class="panel-body">
            <form role="form">
                <fieldset>
                    <div class="form-group">
                        <label for="input_oldpwd"><span class="glyphicon glyphicon-lock"></span>&nbsp;旧密码</label>
                        <input id="input_oldpwd" class="form-control" placeholder="旧密码" name="oldpwd" type="password"
                               autofocus>
                    </div>
                    <div class="col-md-12" id="error_oldpwd"></div>
                    <div class="form-group">
                        <label for="input_newpwd"><span class="glyphicon glyphicon-lock"></span>&nbsp;新密码</label>
                        <input id="input_newpwd" class="form-control" placeholder="新密码" name="newpwd" type="password"
                               autofocus>
                    </div>
                    <div class="col-md-12" id="error_newpwd"></div>
                    <a href="login.html" class="btn btn-success"><span class="glyphicon glyphicon-edit"></span>&nbsp;修改密码</a>
                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $("#m-2").addClass("active");
    });
</script>
{% endblock %}